sudo: required
language: generic 

services:
  - docker
  
before_install:
  - docker build -t emreturgutce/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true emreturgutce/docker-react npm run test
